# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 213f99a47f32b2217997b2bed0dd5d3d912123674fe73b50f69cf4dc349e673e66e5994e9bc8e606ecb110720cd17699b10ca8dc0b22ebf2c793285ec82f7c1f

test:
  secret_key_base: cb3eb6d43e0a38147bb19e4a522b819ee16ca4be5cc3c8fa7b7495d2cb56a6aa27f7f3deceba1d1e4f020d742fe37f042dbb655ff45abcbbc1eff7cecb71eb93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
